import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'zh';

const translations = {
  en: {
    nav: {
      library: 'Library',
      studio: 'Studio',
      transcribe: 'Transcribe',
      audioLab: 'Audio Lab',
      favorites: 'Favorites',
      settings: 'Settings',
    },
    user: {
      pro: 'Pro Plan',
    },
    lib: {
      title: 'Project Library',
      desc: 'Manage and organize your AI-generated soundscapes',
      new: 'Create New Project',
      newProject: 'New Project',
      editProject: 'Edit Project',
      projectName: 'Project Name',
      genre: 'Genre',
      tagsComma: 'Tags (comma separated)',
      cancel: 'Cancel',
      create: 'Create',
      save: 'Save',
      search: 'Search by name, tags, or style...',
      allModels: 'All Models',
      dateCreated: 'Date Created',
      loading: 'Loading projects...',
      edit: 'Edit',
      openInStudio: 'Open in Studio',
      delete: 'Delete',
      comingSoon: 'Coming soon',
      projectNamePlaceholder: 'Enter project name...',
      tagsPlaceholder: 'tag1, tag2',
    },
    studio: {
      compose: 'Compose',
      mastering: 'Mastering',
      share: 'Share',
      shareCopied: 'Link copied to clipboard',
      untitled: 'Untitled Project 4',
      live: 'Live',
      modelConfig: 'Model Config',
      checkpoint: 'Checkpoint',
      tags: 'Tags',
      tagsComma: 'Style / mood / instruments (comma separated)',
      genSettings: 'Gen Settings',
      preset: 'Preset',
      save: 'Save',
      delete: 'Delete Preset',
      creativity: 'Creativity (Temp)',
      topk: 'Top-K Sampling',
      topkHint: 'Number of top candidates for sampling, default 50',
      maxAudioLengthMs: 'Max length max_audio_length_ms',
      maxAudioLengthMsHint: 'Milliseconds, default 240000 (~4 min)',
      cfgScaleHint: 'Conditional guidance strength, default 1.5',
      seamless: 'Seamless Loop',
      refAudio: 'Reference Audio',
      uploadRefAudio: 'Click to upload reference audio (MP3/WAV/FLAC)',
      uploading: 'Uploading...',
      refAudioHint: 'Optional: Upload a reference audio to guide the style of generated music',
      dropAudio: 'Drop audio to guide style (MP3/WAV)',
      taskHistory: 'Task History',
      noTasks: 'No generation tasks yet',
      untitledTask: 'Untitled Task',
      vram: 'VRAM Usage',
      cpuMode: 'CPU Mode',
      lyricEditor: 'LYRIC EDITOR',
      history: 'History',
      close: 'Close',
      genHistory: 'Generation History',
      noLyrics: 'No generated lyrics yet.',
      revert: 'Revert',
      aiSuggest: 'AI Suggest',
      tokens: 'Tokens',
      genre: 'Genre',
      mood: 'Mood',
      promptPlaceholder: 'Specific keywords, topics, or story elements...',
      generate: 'GENERATE',
      generating: 'GENERATING...',
      tracks: 'TRACKS',
      vocals: 'Vocals',
      instr: 'Instr.',
      backing: 'Backing Track',
      verse1: 'Verse 1',
      generated: '(Generated)',
      addSection: '+ Section',
      bpm: 'BPM',
      key: 'Key',
      export: 'Export',
      shortcuts: 'Shortcuts: Space to play/pause, ⌘+Enter to generate',
      clickToSeek: 'Click to seek',
      loading: 'Loading…',
      genError: 'Generation failed',
      updateProjectError: 'Update project failed',
      generateMusic: 'Generate Music',
      generateMusicHint: 'Enter lyrics above to enable',
      projectNotFound: 'Project not found or deleted',
      lyricsError: 'Lyrics generation failed. Check API Key or network.',
      lyricsErrorNoKey: 'API Key not set. Set OPENROUTER_API_KEY or GEMINI_API_KEY in project root .env',
      lyricsErrorEmpty: 'No lyrics content returned',
    },
    transcribe: {
      title: 'Lyrics Transcribe',
      subtitle: 'Upload audio to get lyrics / transcription',
      audioFile: 'Audio file',
      params: 'Parameters',
      submit: 'Submit task',
      submitting: 'Submitting…',
      taskDetail: 'Task detail',
      created: 'Created',
      preview: 'Preview',
      result: 'Transcription result (editable)',
      resultPlaceholder: 'Transcription text',
      saveResult: 'Save result',
      saving: 'Saving…',
      newTask: 'New task',
      selectFile: 'Please select an audio file',
    },
    lab: {
      title: 'AUDIO LAB',
      online: 'ONLINE',
      projects: 'Projects',
      clip: 'Clip',
      metronome: 'METRONOME',
      stemSep: 'Stem Separation',
      addStem: '+ Add Stem',
      promptInterp: 'Prompt Interpolation',
      aiActive: 'AI ACTIVE',
      start: 'START',
      end: 'END',
      exportMix: 'Export Mix',
      exportFormat: 'WAV (32-bit float) • 48kHz',
      comingSoon: 'Coming Soon',
      comingSoonDesc: 'Stem separation feature is under development. Stay tuned!',
    }
  },
  zh: {
    nav: {
      library: '项目库',
      studio: '工作室',
      transcribe: '歌词转录',
      audioLab: '音频实验室',
      favorites: '收藏',
      settings: '设置',
    },
    user: {
      pro: '专业版',
    },
    lib: {
      title: '项目库',
      desc: '管理和组织您的 AI 生成音景',
      new: '新建项目',
      newProject: '新建项目',
      editProject: '编辑项目',
      projectName: '项目名称',
      genre: '音乐类型',
      tagsComma: '标签（逗号分隔）',
      cancel: '取消',
      create: '创建',
      save: '保存',
      search: '按名称、标签或风格搜索...',
      allModels: '所有模型',
      dateCreated: '创建日期',
      loading: '正在加载项目...',
      edit: '编辑',
      openInStudio: '在 Studio 中打开',
      delete: '删除',
      comingSoon: '即将推出',
      projectNamePlaceholder: '输入项目名称...',
      tagsPlaceholder: 'tag1, tag2',
    },
    studio: {
      compose: '作曲',
      mastering: '母带',
      share: '分享',
      shareCopied: '链接已复制到剪贴板',
      untitled: '未命名项目 4',
      live: '实时',
      modelConfig: '模型配置',
      checkpoint: '检查点',
      tags: '标签',
      tagsComma: '风格/情绪/乐器，逗号分隔',
      genSettings: '生成设置',
      preset: '预设',
      save: '保存',
      delete: '删除预设',
      creativity: '创意度 (Temp)',
      topk: 'Top-K 采样',
      topkHint: '采样候选数量，默认 50',
      maxAudioLengthMs: '最大时长 max_audio_length_ms',
      maxAudioLengthMsHint: '毫秒，默认 240000（约 4 分钟）',
      cfgScaleHint: '条件引导强度，默认 1.5',
      seamless: '无缝循环',
      refAudio: '参考音频',
      uploadRefAudio: '点击上传参考音频 (MP3/WAV/FLAC)',
      uploading: '上传中...',
      refAudioHint: '可选：上传参考音频以引导生成音乐的风格',
      dropAudio: '拖放音频以引导风格 (MP3/WAV)',
      taskHistory: '生成历史',
      noTasks: '暂无生成任务',
      untitledTask: '未命名任务',
      vram: '显存使用',
      cpuMode: 'CPU 模式',
      lyricEditor: '歌词编辑器',
      history: '历史',
      close: '关闭',
      genHistory: '生成历史',
      noLyrics: '暂无生成歌词。',
      revert: '恢复',
      aiSuggest: 'AI 建议',
      tokens: 'Token数',
      genre: '流派',
      mood: '情绪',
      promptPlaceholder: '特定关键词、主题或故事元素...',
      generate: '生成',
      generating: '生成中...',
      tracks: '轨道',
      vocals: '人声',
      instr: '器乐',
      backing: '伴奏',
      verse1: '第一节',
      generated: '(已生成)',
      addSection: '+ 章节',
      bpm: 'BPM',
      key: '调式',
      export: '导出',
      shortcuts: '快捷键：空格 播放/暂停，⌘+Enter 生成',
      clickToSeek: '点击跳转',
      loading: '加载中…',
      genError: '生成失败',
      updateProjectError: '更新项目失败',
      generateMusic: '生成音频',
      generateMusicHint: '请在上方填写歌词后启用',
      projectNotFound: '项目不存在或已删除',
      lyricsError: '歌词生成失败，请检查 API Key 或网络',
      lyricsErrorNoKey: '未配置 API Key，请在项目根目录 .env 中设置 OPENROUTER_API_KEY 或 GEMINI_API_KEY',
      lyricsErrorEmpty: '未返回歌词内容',
    },
    transcribe: {
      title: '歌词转录',
      subtitle: '上传音频获取歌词 / 转写文本',
      audioFile: '音频文件',
      params: '参数',
      submit: '提交任务',
      submitting: '提交中…',
      taskDetail: '任务详情',
      created: '创建时间',
      preview: '试听',
      result: '转写结果（可编辑）',
      resultPlaceholder: '转写文本',
      saveResult: '保存结果',
      saving: '保存中…',
      newTask: '新建任务',
      selectFile: '请选择音频文件',
    },
    lab: {
      title: '音频实验室',
      online: '在线',
      projects: '项目',
      clip: '剪辑',
      metronome: '节拍器',
      stemSep: '分轨分离',
      addStem: '+ 添加分轨',
      promptInterp: '提示词插值',
      aiActive: 'AI 激活',
      start: '开始',
      end: '结束',
      exportMix: '导出混音',
      exportFormat: 'WAV (32-bit float) • 48kHz',
      comingSoon: '即将推出',
      comingSoonDesc: '分轨分离功能正在开发中，敬请期待！',
    }
  }
};

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    const keys = key.split('.');
    let value: any = translations[language];
    for (const k of keys) {
      if (value && value[k]) {
        value = value[k];
      } else {
        return key;
      }
    }
    return value as string;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
